-- PROC_MOVE_PRODUCT

-- It works : Good

BEGIN TRANSACTION test_move_product_1
  SET NOCOUNT ON

  DECLARE @PERSOON_ID UNIQUEIDENTIFIER = NEWID();
  DECLARE @ACCOUNT_ID UNIQUEIDENTIFIER = NEWID();
  DECLARE @KAART_ID_1 UNIQUEIDENTIFIER = NEWID();
  DECLARE @KAART_ID_2 UNIQUEIDENTIFIER = NEWID();
  DECLARE @REISPRODUCTID UNIQUEIDENTIFIER = NEWID();

  INSERT INTO dbo.PERSOON (PERSOONID, NAAM, POSTCODE, HUISNUMMER, GEBOORTEDATUM, TELEFOONNUMMER, E_MAILADRES)
  VALUES (@PERSOON_ID, 'Henk Petersen', '4534DS', '23', '01-01-1945', '0123456789', 'h.petersen@gmail.com')

  INSERT INTO dbo.ACCOUNT (ACCOUNTID, PERSOONID, SALDO, REKENINGNUMMER)
  VALUES (@ACCOUNT_ID, @PERSOON_ID, 0, 'NL91ABNA0417164300')

  INSERT INTO dbo.KAART (KAARTID, ACCOUNTID, KAARTNUMMER, KAARTNAAM, VERVALDATUM, KOPPELDATUM)
    VALUES (@KAART_ID_1, @ACCOUNT_ID, '5234267891224512', 'Test naam', DATEADD(day, 3, GETDATE()), GETDATE())

  INSERT INTO dbo.REISPRODUCT (REISPRODUCTID, KAARTID, NAAM, KOPPELDATUM, VERVALDATUM)
    VALUES (@REISPRODUCTID, @KAART_ID_1, 'naam kortingsreisproduct', GETDATE(), DATEADD(day, 3, GETDATE()))

  INSERT INTO dbo.KAART (KAARTID, ACCOUNTID, KAARTNUMMER, KAARTNAAM, VERVALDATUM, KOPPELDATUM)
    VALUES (@KAART_ID_2, @ACCOUNT_ID, '5234267391222512', 'Test naam', DATEADD(day, 3, GETDATE()), GETDATE())

  EXECUTE dbo.PROC_MOVE_PRODUCT @REISPRODUCTID = @REISPRODUCTID, @KAARTID = @KAART_ID_2

ROLLBACK TRANSACTION


-- NO ACCOUNTID
BEGIN TRANSACTION test_move_product_2
  SET NOCOUNT ON

DECLARE @PERSOON_ID UNIQUEIDENTIFIER = NEWID();
DECLARE @ACCOUNT_ID UNIQUEIDENTIFIER = NEWID();
DECLARE @KAART_ID_1 UNIQUEIDENTIFIER = NEWID();
DECLARE @KAART_ID_2 UNIQUEIDENTIFIER = NEWID();
DECLARE @REISPRODUCTID UNIQUEIDENTIFIER = NEWID();

INSERT INTO dbo.PERSOON (PERSOONID, NAAM, POSTCODE, HUISNUMMER, GEBOORTEDATUM, TELEFOONNUMMER, E_MAILADRES)
  VALUES (@PERSOON_ID, 'Henk Petersen', '4534DS', '23', '01-01-1945', '0123456789', 'h.petersen@gmail.com')

INSERT INTO dbo.ACCOUNT (ACCOUNTID, PERSOONID, SALDO, REKENINGNUMMER)
  VALUES (@ACCOUNT_ID, @PERSOON_ID, 0, 'NL91ABNA0417164300')

INSERT INTO dbo.KAART (KAARTID, ACCOUNTID, KAARTNUMMER, KAARTNAAM, VERVALDATUM, KOPPELDATUM)
  VALUES (@KAART_ID_1, @ACCOUNT_ID, '5234267891224512', 'Test naam', DATEADD(day, 3, GETDATE()), GETDATE())

INSERT INTO dbo.REISPRODUCT (REISPRODUCTID, KAARTID, NAAM, KOPPELDATUM, VERVALDATUM)
  VALUES (@REISPRODUCTID, @KAART_ID_1, 'naam kortingsreisproduct', GETDATE(), DATEADD(day, 3, GETDATE()))

INSERT INTO dbo.KAART (KAARTID, ACCOUNTID, KAARTNUMMER, KAARTNAAM, VERVALDATUM, KOPPELDATUM)
  VALUES (@KAART_ID_2, NULL, '5234267391222512', 'Test naam', DATEADD(day, 3, GETDATE()), GETDATE())

EXECUTE dbo.PROC_MOVE_PRODUCT @REISPRODUCTID = @REISPRODUCTID, @KAARTID = @KAART_ID_2

ROLLBACK TRANSACTION

-- WRONG KAARTID

BEGIN TRANSACTION test_move_product_3
SET NOCOUNT ON

DECLARE @PERSOON_ID UNIQUEIDENTIFIER = NEWID();
DECLARE @ACCOUNT_ID UNIQUEIDENTIFIER = NEWID();
DECLARE @KAART_ID_1 UNIQUEIDENTIFIER = NEWID();
DECLARE @KAART_ID_2 UNIQUEIDENTIFIER = NEWID();
DECLARE @REISPRODUCTID UNIQUEIDENTIFIER = NEWID();

INSERT INTO dbo.PERSOON (PERSOONID, NAAM, POSTCODE, HUISNUMMER, GEBOORTEDATUM, TELEFOONNUMMER, E_MAILADRES)
VALUES (@PERSOON_ID, 'Henk Petersen', '4534DS', '23', '01-01-1945', '0123456789', 'h.petersen@gmail.com')

INSERT INTO dbo.ACCOUNT (ACCOUNTID, PERSOONID, SALDO, REKENINGNUMMER)
VALUES (@ACCOUNT_ID, @PERSOON_ID, 0, 'NL91ABNA0417164300')

INSERT INTO dbo.KAART (KAARTID, ACCOUNTID, KAARTNUMMER, KAARTNAAM, VERVALDATUM, KOPPELDATUM)
VALUES (@KAART_ID_1, @ACCOUNT_ID, '5234267891224512', 'Test naam', DATEADD(day, 3, GETDATE()), GETDATE())

INSERT INTO dbo.REISPRODUCT (REISPRODUCTID, KAARTID, NAAM, KOPPELDATUM, VERVALDATUM)
VALUES (@REISPRODUCTID, @KAART_ID_1, 'naam kortingsreisproduct', GETDATE(), DATEADD(day, 3, GETDATE()))

EXECUTE dbo.PROC_MOVE_PRODUCT @REISPRODUCTID = @REISPRODUCTID, @KAARTID = @KAART_ID_2

ROLLBACK TRANSACTION

-- WRONG REISPRODUCTID

BEGIN TRANSACTION test_move_product_4
  SET NOCOUNT ON

  DECLARE @PERSOON_ID UNIQUEIDENTIFIER = NEWID();
  DECLARE @ACCOUNT_ID UNIQUEIDENTIFIER = NEWID();
  DECLARE @KAART_ID_1 UNIQUEIDENTIFIER = NEWID();
  DECLARE @KAART_ID_2 UNIQUEIDENTIFIER = NEWID();
  DECLARE @REISPRODUCTID UNIQUEIDENTIFIER = NEWID();

  INSERT INTO dbo.PERSOON (PERSOONID, NAAM, POSTCODE, HUISNUMMER, GEBOORTEDATUM, TELEFOONNUMMER, E_MAILADRES)
  VALUES (@PERSOON_ID, 'Henk Petersen', '4534DS', '23', '01-01-1945', '0123456789', 'h.petersen@gmail.com')

  INSERT INTO dbo.ACCOUNT (ACCOUNTID, PERSOONID, SALDO, REKENINGNUMMER)
  VALUES (@ACCOUNT_ID, @PERSOON_ID, 0, 'NL91ABNA0417164300')

  INSERT INTO dbo.KAART (KAARTID, ACCOUNTID, KAARTNUMMER, KAARTNAAM, VERVALDATUM, KOPPELDATUM)
  VALUES (@KAART_ID_1, @ACCOUNT_ID, '5234267891224512', 'Test naam', DATEADD(day, 3, GETDATE()), GETDATE())

  INSERT INTO dbo.KAART (KAARTID, ACCOUNTID, KAARTNUMMER, KAARTNAAM, VERVALDATUM, KOPPELDATUM)
  VALUES (@KAART_ID_2, @ACCOUNT_ID, '5234267391222512', 'Test naam', DATEADD(day, 3, GETDATE()), GETDATE())

  EXECUTE dbo.PROC_MOVE_PRODUCT @REISPRODUCTID = @REISPRODUCTID, @KAARTID = @KAART_ID_2

ROLLBACK TRANSACTION