USE smartov -- EXAMPLE DATABASENAME
GO

IF OBJECT_ID('PROC_CREATE_REISPRODUCT', 'P') IS NOT NULL -- EXAMPLE PROCEDURE NAME
  DROP PROCEDURE PROC_CREATE_REISPRODUCT
GO

-- CREATE STORED PROCEDURE
CREATE PROCEDURE PROC_CREATE_REISPRODUCT -- EXAMPLE NAME
    @naam VARCHAR(255), -- EXAMPLE PARAMETERS
    @geldigheid INT
AS
  DECLARE @TranCounter INT;
  SET @TranCounter = @@TRANCOUNT;
  IF @TranCounter > 0
    SAVE TRANSACTION ProcedureSave;
  ELSE
    BEGIN TRANSACTION;
  BEGIN TRY

  IF @geldigheid < 1
      RAISERROR (56260, 16, 1);

  INSERT INTO dbo.REISPRODUCT (REISPRODUCTID, NAAM, GELDIGHEID)
  OUTPUT INSERTED.REISPRODUCTID
  VALUES (
    NEWID(),
    @naam,
    @geldigheid
  )

  IF @TranCounter = 0
    COMMIT TRANSACTION;

  END TRY
  BEGIN CATCH
    IF @TranCounter = 0
      ROLLBACK TRANSACTION;
    ELSE
      IF XACT_STATE() <> -1
        ROLLBACK TRANSACTION ProcedureSave;

    DECLARE @ErrorMessage NVARCHAR(4000);
    DECLARE @ErrorSeverity INT;
    DECLARE @ErrorState INT;
    SELECT @ErrorMessage = ERROR_MESSAGE();
    SELECT @ErrorSeverity = ERROR_SEVERITY();
    SELECT @ErrorState = ERROR_STATE();
    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);
  END CATCH
