USE smartov -- EXAMPLE DATABASENAME
GO

IF OBJECT_ID('PROC_GET_JOURNEYS_FROM_LOCATION', 'P') IS NOT NULL -- EXAMPLE PROCEDURE NAME
  DROP PROCEDURE PROC_GET_JOURNEYS_FROM_LOCATION
GO

-- CREATE STORED PROCEDURE
CREATE PROCEDURE PROC_GET_JOURNEYS_FROM_LOCATION -- EXAMPLE NAME
    @kaartid UNIQUEIDENTIFIER, -- EXAMPLE PARAMETERS
    @locatie UNIQUEIDENTIFIER
AS
  DECLARE @TranCounter INT;
  SET @TranCounter = @@TRANCOUNT;
  IF @TranCounter > 0
    SAVE TRANSACTION ProcedureSave;
  ELSE
    BEGIN TRANSACTION;
  BEGIN TRY

  IF NOT EXISTS(SELECT 1 FROM dbo.KAART WHERE KAARTID = @kaartid)
      RAISERROR (56290, 16, 1)

  IF NOT EXISTS(SELECT 1 FROM dbo.REIS WHERE BEGINPUNT = @locatie)
      RAISERROR (56291, 16, 1)

  SELECT REISID, BEGINPUNT, EINDPUNT, PRIJS, INCHECKDATUM, UITCHECKDATUM, STATION.NAAM
  FROM dbo.REIS JOIN dbo.STATION ON REIS.BEGINPUNT = STATION.STATIONID
  WHERE KAARTID = @kaartid
        AND
        BEGINPUNT = @locatie

  IF @TranCounter = 0
    COMMIT TRANSACTION;

  END TRY
  BEGIN CATCH
    IF @TranCounter = 0
      ROLLBACK TRANSACTION;
    ELSE
      IF XACT_STATE() <> -1
        ROLLBACK TRANSACTION ProcedureSave;

    DECLARE @ErrorMessage NVARCHAR(4000);
    DECLARE @ErrorSeverity INT;
    DECLARE @ErrorState INT;
    SELECT @ErrorMessage = ERROR_MESSAGE();
    SELECT @ErrorSeverity = ERROR_SEVERITY();
    SELECT @ErrorState = ERROR_STATE();
    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);
  END CATCH
