USE smartov -- EXAMPLE DATABASENAME
GO

IF OBJECT_ID('PROC_GET_ACCOUNT_BY_PERSON', 'P') IS NOT NULL -- EXAMPLE PROCEDURE NAME
  DROP PROCEDURE PROC_GET_ACCOUNT_BY_PERSON
GO

-- CREATE STORED PROCEDURE
CREATE PROCEDURE PROC_GET_ACCOUNT_BY_PERSON -- EXAMPLE NAME
    @persoonid UNIQUEIDENTIFIER -- EXAMPLE PARAMETERS
AS
  DECLARE @TranCounter INT;
  SET @TranCounter = @@TRANCOUNT;
  IF @TranCounter > 0
    SAVE TRANSACTION ProcedureSave;
  ELSE
    BEGIN TRANSACTION;
  BEGIN TRY

  IF NOT EXISTS(SELECT 1 FROM dbo.PERSOON WHERE PERSOONID = @persoonid)
      RAISERROR (56270, 16, 1);

  SELECT ACCOUNTID
  FROM dbo.ACCOUNT
  WHERE PERSOONID = @persoonid

  IF @TranCounter = 0
    COMMIT TRANSACTION;

  END TRY
  BEGIN CATCH
    IF @TranCounter = 0
      ROLLBACK TRANSACTION;
    ELSE
      IF XACT_STATE() <> -1
        ROLLBACK TRANSACTION ProcedureSave;

    DECLARE @ErrorMessage NVARCHAR(4000);
    DECLARE @ErrorSeverity INT;
    DECLARE @ErrorState INT;
    SELECT @ErrorMessage = ERROR_MESSAGE();
    SELECT @ErrorSeverity = ERROR_SEVERITY();
    SELECT @ErrorState = ERROR_STATE();
    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);
  END CATCH

  -- EXECUTE sp_addmessage 56270, 16, 'Persoon bestaat niet';